// generated by copilot and chatGPT4 according the type definition in packages/rocket/src/types::ListEntry

// References: https://docs.flutter.dev/cookbook/networking/fetch-data https://docs.flutter.dev/data-and-backend/serialization/json

class ListEntry {
  final String name;
  final String? lastModified;
  final String? etag;
  final String? ownerId;
  final String? ownerName;
  final int? size;
  final String? storageClass;
  final bool isLatest;
  final String? versionId;
  final Map<String, String>? userMetadata;
  final Map<String, String>? userTags;
  final bool isPrefix;
  final bool isDeleteMarker;
  final String? encodingType;

  ListEntry({
    required this.name,
    this.lastModified,
    this.etag,
    this.ownerId,
    this.ownerName,
    this.size,
    this.storageClass,
    required this.isLatest,
    this.versionId,
    this.userMetadata,
    this.userTags,
    required this.isPrefix,
    required this.isDeleteMarker,
    this.encodingType,
  });

  factory ListEntry.fromJson(Map<String, dynamic> json) {
    return ListEntry(
      name: json['name'],
      lastModified: json['last_modified'],
      etag: json['etag'],
      ownerId: json['owner_id'],
      ownerName: json['owner_name'],
      size: json['size'],
      storageClass: json['storage_class'],
      isLatest: json['is_latest'],
      versionId: json['version_id'],
      // TODO find out cast method
      userMetadata: json['user_metadata']?.cast<String, String>(),
      userTags: json['user_tags']?.cast<String, String>(),
      isPrefix: json['is_prefix'],
      isDeleteMarker: json['is_delete_marker'],
      encodingType: json['encoding_type'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'name': name,
      'last_modified': lastModified,
      'etag': etag,
      'owner_id': ownerId,
      'owner_name': ownerName,
      'size': size,
      'storage_class': storageClass,
      'is_latest': isLatest,
      'version_id': versionId,
      'user_metadata': userMetadata,
      'user_tags': userTags,
      'is_prefix': isPrefix,
      'is_delete_marker': isDeleteMarker,
      'encoding_type': encodingType,
    };
  }
}
