// generated by copilot and chatGPT4 according the type definition in packages/rocket/src/types::ListEntry

class TransferTask {
  final String id;
  final String type; // 'upload' or 'download'
  final String name;
  double progress;

  TransferTask({
    required this.id,
    required this.type,
    required this.name,
    required this.progress,
  });
}
